[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = True
mypy_path = .
explicit_package_bases = True
disable_error_code = import-untyped

# Modules without typing stubs
[mypy-firebase_admin.*]
ignore_missing_imports = True

[mypy-pypfopt.*]
ignore_missing_imports = True

[mypy-yfinance.*]
ignore_missing_imports = True

[mypy-google.cloud.*]
ignore_missing_imports = True
